version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind 
        source: . 
        target: /app
    ports:
      - 3000:3000
  redis:
    image: redis
    